admin_panel/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import QuestionnaireListView, QuestionnaireUpdateView, UserOrganizationInfoListView, \
    ParsedDocumentListView, ParseDocumentsView, AdminListView, AdminDeleteView, AdminCreateView, QuestionnaireCreateView, QuestionnaireDeleteView


app_name = 'admin_panel'

urlpatterns = [
    path('', RedirectView.as_view(url='questionnaires/'), name='index'),
    path('start-forms/', UserOrganizationInfoListView.as_view(), name='start-forms'),

    path('parsed-documents/', ParsedDocumentListView.as_view(), name='parsed-documents'),
    path('parse-documents/', ParseDocumentsView.as_view(), name='parse-documents'),

    path('questionnaires/', QuestionnaireListView.as_view(), name='questionnaires'),
    path('create-questionnaire', QuestionnaireCreateView.as_view(), name='create-questionnaire'),
    path('edit-questionnaire/<int:pk>', QuestionnaireUpdateView.as_view(), name='edit-questionnaire'),
    path('delete-questionnaire/<int:pk>', QuestionnaireDeleteView.as_view(), name='delete-questionnaire'),

    path('admins/', AdminListView.as_view(), name='admins'),
    path('create-admin/', AdminCreateView.as_view(), name='create-admin'),
    path('delete-admin/<int:pk>', AdminDeleteView.as_view(), name='delete-admin'),
]

django_forms_reports_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('admin_panel.urls')),
]

main/urls.py
from django.urls import path
from .views import QuestionnaireListView, MainLoginView, MainRegisterView, StartFormView, DoQuestionnaireView, \
    ReportListView, ReportDetailView, ReportDownloadView

from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', QuestionnaireListView.as_view(), name='index'),
    path('questionnaire/<int:pk>', DoQuestionnaireView.as_view(), name='do-questionnaire'),

    path('reports/', ReportListView.as_view(), name='reports'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report'),
    path('report-download/<int:report_id>', ReportDownloadView.as_view(), name='report-download'),

    # path('start-form/', StartFormView.as_view(), name='start-form'),

    path('login/', MainLoginView.as_view(), name='login'),
    path('register/', MainRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
]

admin_panel/models.py
from django.db import models


class ParsedDocument(models.Model):
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255)

admin_panel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.core.exceptions import ValidationError

from django.contrib.auth.models import User


class AdminCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # fields

        self.fields['username'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите логин',
        })
        self.fields['username'].label = 'Логин'

        self.fields['password1'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль',
            'type': 'password'
        })
        self.fields['password1'].label = 'Пароль'

        self.fields['password2'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Повторите пароль',
            'type': 'password'
        })
        self.fields['password2'].label = 'Повторите пароль'

        # error message

        self.error_messages['password_mismatch'] = 'Пароли не совпадают.'

        print(self.error_messages.keys())
        print(self.Meta.model)

    def clean(self):
        cleaned_data = super().clean()

        if User.objects.filter(username=cleaned_data.get('username')).exists():
            raise ValidationError('Пользователь с таким логином уже зарегистрирован!')

        if len(cleaned_data.get('password1')) < 8:
            raise ValidationError('Пароль должен содержать хотя бы 8 символов!')

        if cleaned_data.get('password1').isdigit():
            raise ValidationError('Пароль содержит только цифры!')

admin_panel/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, FormView
from django.views import View

from django.shortcuts import render
from django.urls import reverse_lazy

from django.http import HttpResponse, Http404
from .models import ParsedDocument

from django.contrib.auth.models import User

from .forms import AdminCreateForm

from .mixins import GeneralAdminRequired

from main.models import Questionnaire, UserOrganizationInfo

import json

from parser import Parser


class UserOrganizationInfoListView(ListView):
    model = UserOrganizationInfo
    template_name = 'admin_panel/start_forms_list.html'
    context_object_name = 'start_forms'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['industries'] = list(set([sf.industry for sf in context['start_forms']]))
        context['types_used_systems'] = list(set([sf.type_used_systems for sf in context['start_forms']]))

        return context




class QuestionnaireListView(ListView):
    model = Questionnaire
    template_name = 'admin_panel/questionnaires.html'
    context_object_name = 'questionnaires'
    ordering = ['order']


class QuestionnaireCreateView(View):

    def get(self, request):
        return render(request, 'admin_panel/create_questionnaire.html')

    def post(self, request):
        try:
            data = request.POST
            fields = []

            questionnaire_type = data['type']
            questionnaire_order = data['order']

            for title_key in filter(lambda x: x.endswith('_title'), data):
                _id = title_key.replace('_title', '')

                title = data[title_key]

                designation_key = list(filter(lambda x: x == f'{_id}_designation', data))[0]
                designation = data[designation_key]

                questions = []
                for number_key in filter(lambda x: x.startswith(f'{_id}_') and x.endswith('_number'), data):
                    inner_id = number_key.split('_')[1]

                    number = data[number_key]

                    question_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_question', data))[0]
                    question_text = data[question_text_key]

                    recommendation_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_recommendation', data))[0]
                    recommendation_text = data[recommendation_text_key]

                    criterion_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_criterion', data))[0]
                    criterion_text = data[criterion_text_key]

                    questions.append({
                        'number': number,
                        'question_text': question_text,
                        'recommendation_text': recommendation_text,
                        'criterion_text': criterion_text
                    })

                fields.append({
                    'title': title,
                    'designation': designation,
                    'questions': questions
                })

            if Questionnaire.objects.all().filter(type=questionnaire_type).exists():
                return HttpResponse(json.dumps({'status': 'error', 'message': 'Анкета с таким именем уже существует!'}))

            questionnaire = Questionnaire(type=questionnaire_type, fields=json.dumps(fields), order=questionnaire_order)
            questionnaire.full_clean()

            questionnaire.save()
        except Exception as err:
            print(err)
            return HttpResponse(json.dumps({'status': 'error'}))

        return HttpResponse(json.dumps({'status': 'ok', 'redirect': str(reverse_lazy('admin_panel:questionnaires'))}))


class QuestionnaireDeleteView(DeleteView):
    model = Questionnaire
    template_name = 'admin_panel/questionnaire_delete.html'
    context_object_name = 'questionnaire'
    success_url = reverse_lazy('admin_panel:questionnaires')


class QuestionnaireUpdateView(View):

    def get(self, request, pk):
        if not Questionnaire.objects.all().filter(id=pk).exists():
            return Http404()

        questionnaire = Questionnaire.objects.get(id=pk)
        template_path = 'admin_panel/questionnaire_edit.html' if questionnaire.mode != 'determine' else \
            'admin_panel/questionnaire_determine_edit.html'

        return render(request, template_path, {
            'questionnaire_type': questionnaire.type,
            'questionnaire_id': questionnaire.id,
            'questionnaire_is_active': questionnaire.is_active,
            'questionnaire_order': questionnaire.order, 
            'questionnaire_fields': json.loads(questionnaire.fields)
        })

    def post(self, request, pk):
        if not Questionnaire.objects.all().filter(id=pk).exists():
            raise Http404()

        try:
            data = request.POST
            fields = []

            questionnaire = Questionnaire.objects.get(id=pk)
            questionnaire_type = questionnaire.type
            questionnaire_order = questionnaire.order
            questionnaire_is_active = questionnaire.is_active

            if questionnaire.mode != 'determine':
                questionnaire_type = data['type']
                questionnaire_order = data['order']

                if 'is_active' in data.keys():
                    questionnaire_is_active = True
                else:
                    questionnaire_is_active = False

                for title_key in filter(lambda x: x.endswith('_title'), data):
                    _id = title_key.replace('_title', '')

                    title = data[title_key]

                    designation_key = list(filter(lambda x: x == f'{_id}_designation', data))[0]
                    designation = data[designation_key]

                    questions = []
                    for number_key in filter(lambda x: x.startswith(f'{_id}_') and x.endswith('_number'), data):
                        inner_id = number_key.split('_')[1]

                        number = data[number_key]

                        question_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_question', data))[0]
                        question_text = data[question_text_key]

                        recommendation_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_recommendation', data))[0]
                        recommendation_text = data[recommendation_text_key]

                        criterion_text_key = list(filter(lambda x: x == f'{_id}_{inner_id}_criterion', data))[0]
                        criterion_text = data[criterion_text_key]

                        questions.append({
                            'number': number,
                            'question_text': question_text,
                            'recommendation_text': recommendation_text,
                            'criterion_text': criterion_text
                        })

                    fields.append({
                        'title': title,
                        'designation': designation,
                        'questions': questions
                    })
            else:
                for significance_key in filter(lambda x: x.endswith('_significance'), data):
                    _id = significance_key.replace('_significance', '')

                    significance = data[significance_key]

                    questions = []
                    for indicator_key in filter(lambda x: x.startswith(f'{_id}_') and x.endswith('_indicator'), data):
                        inner_id = indicator_key.split('_')[1]

                        indicator = data[indicator_key]

                        variants = []
                        for title_key in filter(lambda x: x.startswith(f'{_id}_{inner_id}_') and x.endswith('_title'),
                                                data):
                            variant_id = title_key.split('_')[2]

                            title = data[title_key]

                            first_cat_question = data[f'{_id}_{inner_id}_{variant_id}_first_cat_question']
                            second_cat_question = data[f'{_id}_{inner_id}_{variant_id}_second_cat_question']
                            third_cat_question = data[f'{_id}_{inner_id}_{variant_id}_third_cat_question']
                            no_cat_question = data[f'{_id}_{inner_id}_{variant_id}_no_cat_question']

                            variants.append({
                                'title': title,
                                'first_cat_question': first_cat_question,
                                'second_cat_question': second_cat_question,
                                'third_cat_question': third_cat_question,
                                'no_cat_question': no_cat_question,
                            })

                        questions.append({
                            'indicator': indicator,
                            'variants': variants,
                        })

                    fields.append({
                        'significance': significance,
                        'questions': questions,
                    })

            questionnaire.type = questionnaire_type
            questionnaire.order = questionnaire_order
            questionnaire.is_active = questionnaire_is_active
            questionnaire.fields = json.dumps(fields)
            questionnaire.full_clean()

            questionnaire.save()
        except Exception as err:
            print(err)
            return HttpResponse(json.dumps({'status': 'error'}))

        return HttpResponse(json.dumps({'status': 'ok'}))


class ParsedDocumentListView(ListView):
    model = ParsedDocument
    template_name = 'admin_panel/parsed_document_list.html'
    context_object_name = 'parsed_documents'


class ParseDocumentsView(View):

    def get(self, request):
        try:
            parser = Parser()
            docs = parser.parse()

admin_panel/templates/admin_panel/admin_create.html
{% extends 'admin_panel/base.html' %}

{% block title %}Создать администратора{% endblock %}

{% block content %}

<h3>Создать администратора</h3>

<div class="create-admin block">
    <div class="create-admin__error">
        {% if form.errors %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% elif form.username.errors %}
                {% for error in form.username.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% elif form.password1.errors %}
                {% for error in form.password1.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% elif form.password2.errors %}
                {% for error in form.password2.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">{{ form.username.label }}</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">{{ form.password1.label }}</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">{{ form.password2.label }}</label>
            {{ form.password2 }}
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>

{% endblock %}

admin_panel/templates/admin_panel/admin_delete.html
{% extends 'admin_panel/base.html' %}

{% block title %}Удалить админа{% endblock %}

{% block content %}

<h3>Удалить админа</h3>

<div class="delete-admin">
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить админа с юзернеймом <b>{{ admin.username }}</b>?</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>

{% endblock %}

admin_panel/templates/admin_panel/admin_list.html
{% extends 'admin_panel/base.html' %}

{% block title %}Список администраторов{% endblock %}

{% block content %}

<h3>Список администраторов</h3>

<div class="admins-table block">
    <a href="{% url 'admin_panel:create-admin' %}" class="btn btn-primary">Создать администратора</a>
    <hr>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Логин</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for admin in admins %}
          <tr>
            <td>{{ admin.username }}</td>
            <td><a href="{% url 'admin_panel:delete-admin' admin.id %}" class="btn btn-danger btn-sm">Удалить</a></td>
          </tr>
          {% empty %}
          <tr>
              <td>Пусто...</td>
              <td></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

admin_panel/templates/admin_panel/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">

    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'main/css/main.min.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header class="header border-bottom">
        <div class="container">
            <div class="header-container d-flex flex-wrap justify-content-between py-3">
                <a href="{% url 'admin_panel:questionnaires' %}" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Админ-панель</span>
                </a>
                {% with request.resolver_match.url_name as url_name %}
                <ul class="nav nav-pills">
                    <li class="nav-item"><a href="{% url 'admin_panel:questionnaires' %}" class="nav-link {% if url_name == 'questionnaires' %}active{% endif %}">Анкеты</a></li>
                    <li class="nav-item"><a href="{% url 'admin_panel:start-forms' %}" class="nav-link {% if url_name == 'start-forms' %}active{% endif %}">Общие сведения</a></li>
                    <li class="nav-item"><a href="{% url 'admin_panel:parsed-documents' %}" class="nav-link {% if url_name == 'parsed-documents' %}active{% endif %}">Обновления</a></li>
                    {% if request.user.is_general_admin %}
                    <li class="nav-item"><a href="{% url 'admin_panel:admins' %}" class="nav-link {% if url_name == 'admins' %}active{% endif %}">Администраторы</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Сайт для пользователя</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Выход</a></li>
                </ul>
                {% endwith %}
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'main/js/bootstrap.bundle.min.js' %}" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'admin_panel/js/main.js' %}"></script>
  </body>
</html>

admin_panel/templates/admin_panel/create_questionnaire.html
{% extends 'admin_panel/base.html' %}

{% load static %}

{% block title %}Создать новую анкету{% endblock %}

{% block content %}

<h3>Создать новую анкету</h3>

<div class="create-questionnaire">
    <form action="" id="create-questionnaire-form">
        {% csrf_token %}
        <p><label>Название анкеты:</label></p>
        <p><input class="form-control" type="text" name="type" value="" required></p>
        <p><label>Тип анкеты:</label></p>
        <p><select class="form-select" name="order" required>
            <option value="" selected disabled>Укажите тип анкеты</option>
            <option value="1">Первая категория значимости</option>
            <option value="2">Вторая категория значимости</option>
            <option value="3">Третья категория значимости</option>
            <option value="4">Без категории значимости</option>
            <option value="5">Дополнительная анкета</option>
        </select></p>
        <div class="create-questionnaire__items">
        </div>
        <div class="create-questionnaire__add-item">
            <a href="#" class="link-info">Добавить меру обеспечения безопасности</a>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <div class="form-alerts">
            <div class="alert alert-success alert-dismissible form-alerts__success">Сохранено!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
            <div class="alert alert-danger alert-dismissible form-alerts__error">Неизвестная ошибка!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
        </div>
    </form>
</div>

{% endblock %}

admin_panel/templates/admin_panel/parsed_document_list.html
{% extends 'admin_panel/base.html' %}

{% block title %}Обновления в документах{% endblock %}

{% block content %}

<h3>Обвновления в документах</h3>

<br>
<form action="{% url 'admin_panel:parse-documents' %}" method="GET" id="parse-documents-form">
    <button class="btn btn-primary" type="submit">Обновить документы</button>
    <div class="form-alerts">
        <div class="alert alert-success alert-dismissible form-alerts__success">Документы были успешно обновлены! Перезагрузите страницу!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
        <div class="alert alert-danger alert-dismissible form-alerts__error">Неизвестная ошибка!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
    </div>
</form>

<div class="parsed-docs block">
    <ul class="list-group list-group-flush">
        {% for doc in parsed_documents %}
        <li class="list-group-item"><a href="{{ doc.link }}" target="_blank">{{ doc.title }}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

admin_panel/templates/admin_panel/questionnaire_delete.html
{% extends 'admin_panel/base.html' %}

{% block title %}Удалить анкету{% endblock %}

{% block content %}

<h3>Удалить анкету</h3>

<div class="delete-questionnaire">
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить анкету с название <b>{{ questionnaire.type }}</b>?</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>

{% endblock %}

admin_panel/templates/admin_panel/questionnaire_edit.html
{% extends 'admin_panel/base.html' %}

{% load static %}

{% block title %}Редактировать анкету{% endblock %}

{% block content %}

<h3>Редактировать анкету</h3>

<div class="edit-questionnaire">
    <form action="" id="edit-questionnaire-form">
        {% csrf_token %}
        <p><label>Название анкеты:</label></p>
        <p><input class="form-control" type="text" name="type" value="{{ questionnaire_type }}" required></p>
        <p><label>Тип анкеты:</label></p>
        <p><select class="form-select" name="order" required>
            <option value="1" {% if questionnaire_order == 1 %} selected {% endif %}>Первая категория значимости</option>
            <option value="2" {% if questionnaire_order == 2 %} selected {% endif %}>Вторая категория значимости</option>
            <option value="3" {% if questionnaire_order == 3 %} selected {% endif %}>Третья категория значимости</option>
            <option value="4" {% if questionnaire_order == 4 %} selected {% endif %}>Без категории значимости</option>
            <option value="5" {% if questionnaire_order == 5 %} selected {% endif %}>Дополнительная анкета</option>
        </select></p>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="is_active" value="active" id="flexCheckDefault" {% if questionnaire_is_active %} checked {% endif %}>
          <label class="form-check-label" for="flexCheckDefault">
            Анкета активна
          </label>
        </div>
        <br>
        <div class="edit-questionnaire__items">
            {% for field in questionnaire_fields %}
                <div class="edit-questionnaire__item block" data-item-id="{{ forloop.counter }}">
                    <div class="edit-questionnaire__item-delete">
                        <img src="{% static 'main/images/delete.svg' %}">
                    </div>
                    <div class="edit-questionnaire__item-title">
                        <label class="form-label">Мера</label>
                        <input type="text" class="form-control" name="{{ forloop.counter }}_title" value="{{ field.title }}" required>
                    </div>
                    <div class="edit-questionnaire__item-designation">
                        <label class="form-label">Обозначние меры</label>
                        <input type="text" class="form-control" name="{{ forloop.counter }}_designation" value="{{ field.designation }}" required>
                    </div>
                    <hr>
                    <div class="edit-questionnaire__item-fields">
                        <label class="form-label">Поля меры обеспечения безопасности значимого объекта</label>
                        {% for question in field.questions %}
                            <div class="edit-questionnaire__item-field" data-field-id="{{ forloop.counter }}">
                                <div class="edit-questionnaire__item-field__number">
                                    <input type="text" class="form-control" placeholder="Номер" name="{{ forloop.parentloop.counter }}_{{ forloop.counter }}_number" value="{{ question.number }}" required>
                                </div>
                                <div class="edit-questionnaire__item-field__question">
                                    <input type="text" class="form-control" placeholder="Вопрос" name="{{ forloop.parentloop.counter }}_{{ forloop.counter }}_question" value="{{ question.question_text }}" required>
                                </div>
                                <div class="edit-questionnaire__item-field__delete">
                                    <img src="{% static 'main/images/delete.svg' %}">
                                </div>
                                <div class="edit-questionnaire__item-field__recommendation">
                                    <textarea name="{{ forloop.parentloop.counter }}_{{ forloop.counter }}_recommendation" cols="30" placeholder="Рекоммендации" rows="5" class="form-control" required>{{ question.recommendation_text }}</textarea>
                                    <textarea name="{{ forloop.parentloop.counter }}_{{ forloop.counter }}_criterion" cols="30" placeholder="Критерий оценки" rows="5" class="form-control">{{ question.criterion_text }}</textarea>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <hr>
                    <div class="edit-questionnaire__item-add-field">
                        <a class="link-info" href="#">Добавить вопрос</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="edit-questionnaire__add-item">
            <a href="#" class="link-info">Добавить меру обеспечения безопасности</a>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'admin_panel:delete-questionnaire' questionnaire_id %}" class="btn btn-danger">Удалить</a>
        <div class="form-alerts">
            <div class="alert alert-success alert-dismissible form-alerts__success">Сохранено!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
            <div class="alert alert-danger alert-dismissible form-alerts__error">Неизвестная ошибка!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
        </div>
    </form>
</div>

{% endblock %}

admin_panel/templates/admin_panel/questionnaires.html
{% extends 'admin_panel/base.html' %}

{% load static %}

{% block title %}Анкеты{% endblock %}

{% block content %}

<h3>Анкеты</h3>

<div class="questionnaires">
    <div class="row">
        {% for questionnaire in questionnaires %}
        <div class="col-sm-3">
            <div class="card questionnaires__item">
                <div class="card-body">
                    <img src="{% static 'main/images/questionnaire.svg' %}">
                    <h5 class="card-title">{{ questionnaire.type }}</h5>
                    <a href="{% url 'admin_panel:edit-questionnaire' questionnaire.id %}" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-sm-3">
            <div class="card questionnaires__item">
                <div class="card-body">
                    <img src="{% static 'main/images/plus.svg' %}">
                    <h5 class="card-title">Добавить новую<br> анкету</h5>
                    <a href="{% url 'admin_panel:create-questionnaire' %}" class="btn btn-outline-primary">Добавить анкету</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}