admin_panel/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import QuestionnaireListView, QuestionnaireUpdateView, UserOrganizationInfoListView, \
    ParsedDocumentListView, ParseDocumentsView, AdminListView, AdminDeleteView, AdminCreateView, QuestionnaireCreateView, QuestionnaireDeleteView


app_name = 'admin_panel'

urlpatterns = [
    path('', RedirectView.as_view(url='questionnaires/'), name='index'),
    path('start-forms/', UserOrganizationInfoListView.as_view(), name='start-forms'),

    path('parsed-documents/', ParsedDocumentListView.as_view(), name='parsed-documents'),
    path('parse-documents/', ParseDocumentsView.as_view(), name='parse-documents'),

    path('questionnaires/', QuestionnaireListView.as_view(), name='questionnaires'),
    path('create-questionnaire', QuestionnaireCreateView.as_view(), name='create-questionnaire'),
    path('edit-questionnaire/<int:pk>', QuestionnaireUpdateView.as_view(), name='edit-questionnaire'),
    path('delete-questionnaire/<int:pk>', QuestionnaireDeleteView.as_view(), name='delete-questionnaire'),

    path('admins/', AdminListView.as_view(), name='admins'),
    path('create-admin/', AdminCreateView.as_view(), name='create-admin'),
    path('delete-admin/<int:pk>', AdminDeleteView.as_view(), name='delete-admin'),
]

django_forms_reports_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('admin_panel.urls')),
]

main/urls.py
from django.urls import path
from .views import QuestionnaireListView, MainLoginView, MainRegisterView, StartFormView, DoQuestionnaireView, \
    ReportListView, ReportDetailView, ReportDownloadView

from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', QuestionnaireListView.as_view(), name='index'),
    path('questionnaire/<int:pk>', DoQuestionnaireView.as_view(), name='do-questionnaire'),

    path('reports/', ReportListView.as_view(), name='reports'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report'),
    path('report-download/<int:report_id>', ReportDownloadView.as_view(), name='report-download'),

    # path('start-form/', StartFormView.as_view(), name='start-form'),

    path('login/', MainLoginView.as_view(), name='login'),
    path('register/', MainRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils import timezone

import json


class Questionnaire(models.Model):
    TYPE_CHOICES = (
        ('first', 'Анкета первой категории значимости'),
        ('second', 'Анкета второй категории значимости'),
        ('third', 'Анкета третей категории значимости'),
        ('without', 'Анкета без категории значимости'),
        ('determine', 'Анкета определения категории значимости'),
    )
    type = models.CharField(max_length=200, unique=True)
    mode = models.CharField(max_length=200, choices=(('determine', 'Анкета определения категории'), ('simple', 'Обычная анкета')), default='simple')
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    fields = models.TextField()

    def __str__(self):
        return f'{self.type}'

    def clean(self):
        try:
            fields = json.loads(self.fields)

            if self.mode != 'determine':
                for field in fields:
                    field_keys = field.keys()

                    for x in ['title', 'designation', 'questions']:
                        if x not in field_keys:
                            raise ValidationError('Not valid fields')

                    if not isinstance(field['questions'], list):
                        raise ValidationError('Not valid fields')

                    for x in field['questions']:
                        if not isinstance(x, dict):
                            raise ValidationError('Not valid fields')

                        question_keys = x.keys()
                        for y in ['number', 'question_text', 'recommendation_text', 'criterion_text']:
                            if y not in question_keys:
                                raise ValidationError('Not valid fields')
            else:
                for field in fields:
                    field_keys = field.keys()

                    for key in ['significance', 'questions']:
                        if key not in field_keys:
                            raise ValidationError('Not valid fields')

                    for question in field['questions']:
                        if not isinstance(question, dict):
                            raise ValidationError('Not valid fields')

                        question_keys = question.keys()
                        for key in ['indicator', 'variants']:
                            if key not in question_keys:
                                raise ValidationError('Not valid fields')

                        for variant in question['variants']:
                            if not isinstance(variant, dict):
                                raise ValidationError('Not valid fields')

                            variant_keys = variant.keys()
                            for key in ['title', 'third_cat_question', 'second_cat_question', 'first_cat_question',
                                        'no_cat_question']:
                                if key not in variant_keys:
                                    raise ValidationError('Not valid fields')
        except ValueError as err:
            raise ValidationError('Not valid JSON')
        except Exception as err:
            raise ValidationError('Not valid JSON')


class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    questionnaire_title = models.CharField(max_length=100)
    report = models.TextField()

    industry = models.CharField(max_length=100)
    type_used_systems = models.CharField(max_length=100)

    done_date = models.DateTimeField(auto_now_add=True)


    def get_done_date(self):
        tz = timezone.get_default_timezone()
        return self.done_date.astimezone(tz).strftime('%d.%m.%Y %H:%M')


class UserOrganizationInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    industry = models.CharField(max_length=100)
    type_used_systems = models.CharField(max_length=100)

    questionnaire_title = models.CharField(max_length=100)
    done_date = models.DateTimeField(auto_now_add=True)

    def get_done_date(self):
        tz = timezone.get_default_timezone()
        return self.done_date.astimezone(tz).strftime('%d.%m.%Y %H:%M')

    def __str__(self):
        return f'{str(self.user).capitalize()}s organization info'

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import UserOrganizationInfo


class MainLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # fields

        self.fields['username'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите логин',
        })
        self.fields['username'].label = 'Логин'

        self.fields['password'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль',
            'type': 'password'
        })
        self.fields['password'].label = 'Пароль'

        # error message

        self.error_messages['invalid_login'] = 'Пожалуйста введите корректный логин и пароль.'
        self.error_messages['inactive'] = 'Этот аккаунт не активен в данный момент.'


class MainRegisterForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # fields

        self.fields['username'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите логин',
        })
        self.fields['username'].label = 'Логин'

        self.fields['password1'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль',
            'type': 'password'
        })
        self.fields['password1'].label = 'Пароль'

        self.fields['password2'].widget = forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль повторно',
            'type': 'password'
        })
        self.fields['password2'].label = 'Повторите пароль'


class StartFormForm(forms.ModelForm):

    class Meta:
        model = UserOrganizationInfo
        fields = ['industry', 'type_used_systems']

        widgets = {
            'industry': forms.TextInput(attrs={'class': 'form-control'}),
            'type_used_systems': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'industry': 'Отрасль предприятия',
            'type_used_systems': 'Тип используемых систем',
        }

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.http import HttpResponse, Http404

from django.views.generic.edit import FormView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView

from django.views import View

from django.templatetags.static import static

from .forms import MainLoginForm, MainRegisterForm, StartFormForm
from .models import UserOrganizationInfo, Questionnaire, Report

from .mixins import LoginRequiredMixin

from .utils import render_to_pdf

import json


class DoQuestionnaireView(LoginRequiredMixin, View):

    def get(self, request, pk):
        if not Questionnaire.objects.filter(id=pk).exists():
            return redirect('index')

        questionnaire = Questionnaire.objects.get(id=pk)

        if not questionnaire.is_active:
            return redirect('index')

        template_path = 'main/do_questionnaire_determine.html' if questionnaire.mode == 'determine'\
            else 'main/do_questionnaire.html'

        return render(request, template_path, {
            'questionnaire_type': questionnaire.type,
            'questionnaire_fields': json.loads(questionnaire.fields)
        })

    def post(self, request, pk):
        if not Questionnaire.objects.filter(id=pk).exists():
            raise Http404()

        try:
            data = request.POST

            questionnaire = Questionnaire.objects.get(id=pk)
                
            if not questionnaire.is_active:
                return redirect('index')

            if questionnaire.mode != 'determine':
                fields = json.loads(questionnaire.fields)
                report_fields = {}

                for answer_key in filter(lambda x: x.endswith('_answer'), data):
                    field_id, question_id, _ = answer_key.split('_')
                    field_id, question_id = int(field_id) - 1, int(question_id) - 1

                    title = fields[field_id]['title']
                    if title not in report_fields.keys():
                        report_fields[title] = []

                    question = fields[field_id]['questions'][question_id]['question_text']
                    recommendation = fields[field_id]['questions'][question_id]['recommendation_text']
                    answer = data[answer_key]

                    report_fields[title].append({'is_provided': answer == 'provided', 'question': question,
                                                 'recommendation': recommendation})

                industry = data['industry'] if data['industry'] != 'another' else data['industry-another']
                type_used_systems = data['type_used_systems'] if data['type_used_systems'] != 'another' else data['type_used_systems-another']

                report = Report(questionnaire_title=questionnaire.type, user=request.user, report=json.dumps(
                    report_fields), industry=industry, type_used_systems=type_used_systems)
                report.save()

                userOrganizationInfo = UserOrganizationInfo(user=request.user, questionnaire_title=questionnaire.type, industry=industry, type_used_systems=type_used_systems)
                userOrganizationInfo.save()

                return HttpResponse(json.dumps({'status': 'ok', 'redirect': str(reverse_lazy('index'))}))
            else:
                determined_category = 'non'

                if len(list(filter(lambda x: x == 'first_cat_question', data.values()))) > 0:
                    determined_category = 'first'
                elif len(list(filter(lambda x: x == 'second_cat_question', data.values()))) > 0:
                    determined_category = 'second'
                elif len(list(filter(lambda x: x == 'third_cat_question', data.values()))) > 0:
                    determined_category = 'third'

                return HttpResponse(json.dumps({'status': 'ok', 'determined_category': determined_category}))
        except Exception as err:
            print(err)
            return HttpResponse(json.dumps({'status': 'error'}))


class QuestionnaireListView(LoginRequiredMixin, ListView):
    model = Questionnaire
    template_name = 'main/index.html'
    context_object_name = 'questionnaires'
    ordering = ['order']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['questionnaires'] = context['questionnaires'].filter(is_active=True)

        return context



class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'main/report_list.html'
    context_object_name = 'reports'
    ordering = ['-done_date']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['reports'] = context['reports'].filter(user=self.request.user)

        return context


class ReportDownloadView(LoginRequiredMixin, View):

    def get(self, request, report_id):
        if not Report.objects.filter(id=report_id).exists():
            raise Http404()

        report = Report.objects.get(id=report_id)

        context = {'report': report, 'report_fields': json.loads(report.report),
                   'font_path': f'{request.build_absolute_uri(static("main/fonts/tahoma.ttf"))}',
                   'font_bold_path': f'{request.build_absolute_uri(static("main/fonts/tahoma_bold.ttf"))}'}

        for field_key in context['report_fields']:
            fields = context['report_fields'][field_key]
            context['report_fields'][field_key] = {
                'fields': fields,
                'not_provided_count': len(list(filter(lambda x: not x[
                    'is_provided'], context['report_fields'][field_key])))
            }

        pdf = render_to_pdf('main/report_pdf.html', context)

        filename = f'{report.done_date}.pdf'
        content = f'attachment; filename="{filename}"'

        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = content

        return response


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'main/report_detail.html'
    context_object_name = 'report'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['report_fields'] = json.loads(context['report'].report)

        for field_key in context['report_fields']:
            fields = context['report_fields'][field_key]
            context['report_fields'][field_key] = {
                'fields': fields,
                'not_provided_count': len(list(filter(lambda x: not x[
                    'is_provided'], context['report_fields'][field_key])))
            }

        return context


class StartFormView(LoginRequiredMixin, CreateView):
    template_name = 'main/start_form.html'
    model = UserOrganizationInfo
    form_class = StartFormForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(StartFormView, self).form_valid(form)


class MainLoginView(LoginView):
    template_name = 'main/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    authentication_form = MainLoginForm

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse_lazy('admin_panel:questionnaires')

        return reverse_lazy('index')


class MainRegisterView(FormView):
    template_name = 'main/register.html'
    form_class = MainRegisterForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        return super(MainRegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('login')

        return super(MainRegisterView, self).get(*args, **kwargs)

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">

    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'main/css/main.min.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <header class="header border-bottom">
        <div class="container">
            <div class="header-container d-flex flex-wrap justify-content-between py-3">
                <a href="{% url 'index' %}" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">ИБ предприятий ТЭК</span>
                </a>
                {% with request.resolver_match.url_name as url_name %}
                <ul class="nav nav-pills">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link {% if url_name == 'index' %}active{% endif %}">Анкеты</a></li>
                    <li class="nav-item"><a href="{% url 'reports' %}" class="nav-link {% if url_name == 'reports' %}active{% endif %}">Отчеты</a></li>
                    {% if request.user.is_superuser %}
                    <li class="nav-item"><a href="{% url 'admin_panel:index' %}" class="nav-link">Админ-панель</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Выход</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link {% if url_name == 'login' %}active{% endif %}">Вход</a></li>
                    <li class="nav-item"><a href="{% url 'register' %}" class="nav-link {% if url_name == 'register' %}active{% endif %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% endwith %}
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'main/js/bootstrap.bundle.min.js' %}" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/js/main.js' %}"></script>
  </body>
</html>

main/templates/main/do_questionnaire.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}{{ questionnaire_type }}{% endblock %}

{% block content %}

<h3>{{ questionnaire_type }}</h3>

<div class="do-questionnaire">
    <form action="POST" id="do-questionnaire-form">
        {% csrf_token %}
        <p><label for="">Отрасль предприятия</label></p>
        <p>
            <select class="form-select" name="industry" aria-label="Отрасль предприятия" required>
                <option disabled selected value="">Отрасль предприятия</option>
                <option value="Электроэнергетика">Электроэнергетика</option>
                <option value="Нефтегазовая промышленность">Нефтегазовая промышленность</option>
                <option value="Химическая промышленность">Химическая промышленность</option>
                <option value="Металлургическая промышленность">Металлургическая промышленность</option>
                <option value="Сельскохозяйственная отрасль">Сельскохозяйственная отрасль</option>
                <option value="Автомобильная промышленность">Автомобильная промышленность</option>
                <option value="Автоматизация инженерных систем">Автоматизация инженерных систем</option>
                <option value="Транспортные системы (включая аэропорты)">Транспортные системы (включая аэропорты)</option>
                <option value="Пищевая промышленность">Пищевая промышленность</option>
                <option value="Жилищно-коммунальное хозяйство">Жилищно-коммунальное хозяйство</option>
                <option value="another">Другое</option>
            </select>
            <p>
                <input type="text" class="form-control" style="display: none;" name="industry-another" placeholder="Свой вариант">
            </p>
        </p>
        <p><label for="">Тип используемых систем</label></p>
        <p>
            <select class="form-select" name="type_used_systems" required aria-label="Тип используемых систем">
                <option disabled selected value="">Тип используемых систем</option>
                <option value="Автоматизированные системы управления технологическими процессами (АСУ ТП)">Автоматизированные системы управления технологическими процессами (АСУ ТП)</option>
                <option value="Распределенные системы управления (РСУ)">Распределенные системы управления (РСУ)</option>
                <option value="Системы автоматизированного технологического управления (АСТУ)">Системы автоматизированного технологического управления (АСТУ)</option>
                <option value="Системы релейной защиты и автоматики (РЗА)">Системы релейной защиты и автоматики (РЗА)</option>
                <option value="Системы противоаварийной защиты (ПАЗ)">Системы противоаварийной защиты (ПАЗ)</option>
                <option value="Системы телемеханики (СТМ)">Системы телемеханики (СТМ)</option>
                <option value="Системы управления инженерными подсистемами">Системы управления инженерными подсистемами</option>
                <option value="Робототехнические системы">Робототехнические системы</option>
                <option value="Системы промышленного Интернета вещей (IIoT)">Системы промышленного Интернета вещей (IIoT)</option>
                <option value="another">Другое</option>
            </select>
        </p>
        <p>
            <input type="text" class="form-control" style="display: none;" name="type_used_systems-another" placeholder="Свой вариант">
        </p>
        <br>
        {% for field in questionnaire_fields %}
            <div class="do-questionnaire__item block">
                <h5>{{ field.title }} ({{ field.designation }})</h5>
                <hr>
                {% for question in field.questions %}
                    <div class="do-questionnaire__item-field">
                        <div class="do-questionnaire__item-field__number">{{ field.designation }}. {{ question.number }}</div>
                        <div class="do-questionnaire__item-field__question">{{ question.question_text }}</div>
                        <div class="do-questionnaire__item-field__input">
                            <select class="form-select" name="{{ forloop.parentloop.counter }}_{{ forloop.counter }}_answer" required>
                                <option selected disabled value="">Выберите вариант ответа</option>
                                <option value="provided">Обеспечивается</option>
                                <option value="not-provided">Не обеспечивается</option>
                            </select>
                        </div>
                        <div class="do-questionnaire__item-field__criterion">
                            {% if question.criterion_text|length > 0 %}
                            <div class="do-questionnaire__item-field__criterion-show btn btn-sm btn-outline-info">Критерий оценки</div>
                            <div class="do-questionnaire__item-field__criterion-text">
                                <br><span><strong>Критерий оценки:</strong></span>
                                <p style="margin-top: 5px">{{ question.criterion_text }}</p>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Завершить анкету</button>
        <div class="form-alerts">
            <div class="alert alert-success alert-dismissible form-alerts__success">Анкета была отправлена!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
            <div class="alert alert-danger alert-dismissible form-alerts__error">Неизвестная ошибка!<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
        </div>
    </form>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Главная{% endblock %}

{% block content %}

<h3>Доступные анкеты</h3>

<div class="questionnaires">
    <div class="row">
        {% for questionnaire in questionnaires %}
        <div class="col-sm-3">
            <div class="card questionnaires__item">
                <div class="card-body">
                    <img src="{% static 'main/images/questionnaire.svg' %}">
                    <h5 class="card-title">{{ questionnaire.type }}</h5>
                    <a href="{% url 'do-questionnaire' questionnaire.id %}" class="btn btn-primary">Перейти</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Авторизация{% endblock %}

{% block content %}

<div class="auth block">
    <div class="auth__errors">
        {% if form.errors %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">{{ form.username.label }}</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">{{ form.password.label }}</label>
            {{ form.password }}
        </div>
        <button type="submit" class="btn btn-primary">Авторизироваться</button>
    </form>
</div>

{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<div class="register block">
    <div class="register__error">
        {% if form.errors %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">{{ form.username.label }}</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">{{ form.password1.label }}</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">{{ form.password2.label }}</label>
            {{ form.password2 }}
        </div>
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
</div>

{% endblock %}

main/templates/main/report_detail.html
{% extends 'main/base.html' %}

{% block title %}Результат отчета{% endblock %}

{% block content %}

<h3>Результат отчета</h3>

<div class="report">
    <h5>{{ report.questionnaire_title }}</h5>
    <p>Дата прохождения: {{ report.get_done_date }}</p>
    <p>Отрасль предприятия: {{ report.industry }}</p>
    <p>Тип используемых систем: {{ report.type_used_systems }}</p>
    <br>
    {% for title, questions in report_fields.items %}
        <div class="report__item block">
            <h4>Мера "{{ title }}"</h4>
            {% if questions.not_provided_count == 0 %}
                <p class="report__item-description report__item-description--good">Мера соблюдена и требования удовлетворены полностью.</p>
            {% elif questions.not_provided_count == questions.fields|length %}
                <p class="report__item-description report__item-description--bad">Мера не соблюдается, требования мер не удовлетворены:</p>
            {% else %}
                <p class="report__item-description report__item-description--middle">Мера соблюдена частично.</p>
            {% endif %}
            {% for question in questions.fields %}
                <div class="report__item-question report__item-question--{% if not question.is_provided %}not-{% endif %}provided">
                    {{ question.question }}
                </div>
                {% if not question.is_provided %}
                    <p class="report__item-recommendation">
                        {{ question.recommendation }}
                    </p>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
    <a href="{% url 'report-download' report.id %}" target="_blank" class="btn btn-primary">Сохранить в PDF</a>
</div>

{% endblock %}